// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPws9KZge1NdREX83p2gn9HSinvADZ9A',
    appId: '1:465544903690:web:3b8880236fa3fa55e3f3f3',
    messagingSenderId: '465544903690',
    projectId: 'camion-b2672',
    authDomain: 'camion-b2672.firebaseapp.com',
    storageBucket: 'camion-b2672.appspot.com',
    measurementId: 'G-5NPKYJ17CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPL7TJJyKd3hwKNgk48On_gyiHFNZOk9o',
    appId: '1:465544903690:android:3cf9b4c4f4e6273de3f3f3',
    messagingSenderId: '465544903690',
    projectId: 'camion-b2672',
    storageBucket: 'camion-b2672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOXqoVYjo5Vq7foi_pnqkLgYnVxOSQTg',
    appId: '1:465544903690:ios:2d0097dbc65404e4e3f3f3',
    messagingSenderId: '465544903690',
    projectId: 'camion-b2672',
    storageBucket: 'camion-b2672.appspot.com',
    iosBundleId: 'com.acrossmena.camion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOXqoVYjo5Vq7foi_pnqkLgYnVxOSQTg',
    appId: '1:465544903690:ios:ecd4e4a6a9b75713e3f3f3',
    messagingSenderId: '465544903690',
    projectId: 'camion-b2672',
    storageBucket: 'camion-b2672.appspot.com',
    iosBundleId: 'com.acrossmena.camion.RunnerTests',
  );
}
